
server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/lin034/cursoMicroservicios.git
          search-paths: config-data
  application:
    name: config-servicio